### ISSUE TITLE
Find the better way to get external libraries API

### ISSUE THREAD

**Issue by astrochili** [astrochili/vscode-defold#19]
Defold has more comfortable way to interact with external libraries, witch are not available in VSCode. There is a hack [way to get library headers](https://github.com/astrochili/defold-vscode-guide#libraries) in VSCode, but, again, it is done manually.

May be it's possible to automate the process of unzipping and removing C++ files?

**Comment by mikatuo** [comment]
I implemented this feature in [the extension](https://forum.defold.com/t/vscode-extensions-for-defold-aka-defold-extension-pack/72508/17).
