### ISSUE TITLE
Can't install astronachos.defold because it requires VS Code 1.79.0

### ISSUE THREAD

**Issue by Makana-Grey** [astrochili/vscode-defold#29]
When I click install in vs code, it show me message - Can't install **astronachos.defold** extension because it is not compatible with the current version of Visual Studio Code (version 1.74.2)

**Comment by astrochili** [comment]
Version 1.79.0 or higher is required to install the extension. It happened that way, as it's the version on which the extension was developed.

Just update the VSCode or... tell me if this is an issue for you and I will try to chage the version (I'll need to to install an older VSCode to bundle the extension)

**Comment by Makana-Grey** [comment]
Thank you so match. It work.
