### ISSUE TITLE
Incorrect path for Code.exe on Windows in readme section "Opening Files from Defold"

### ISSUE THREAD

**Issue by redoak** [astrochili/vscode-defold#35]
The default install path for VSCode is `C:\Users\{Username}\AppData\Local\Programs\Microsoft VS Code\Code.exe`

FYI, I tried using `%LocalAppData%` in the Custom Editor path to get rid of the username, but it appears not to be supported by Defold. I have "Code.exe" in my path, but it doesn't work either. So the full, real path is needed.

If I specify the dot in Open File, i.e. `. {file}`, it would at first open-and-create the double-clicked file in the root of the directory. When I removed the dot it worked fine. Now, when I attempted to reproduce the issue it, it works fine with the dot. No idea why.

**Comment by astrochili** [comment]
So we don't have a universal path for Windows and the current is no more that example. I don't even know what the solution is here then, except to manually specify the full path.

**Comment by redoak** [comment]
I think it's fine to require the path to be manually specified. My thought was only that you may want to change the path given in the readme, along with a note, to avoid confusion when the file isn't found given the current path. The rest was only FYI.
