### ISSUE TITLE
Unable to successfully "Sync Dependencies API Annotations"

### ISSUE THREAD

**Issue by swajj** [astrochili/vscode-defold#37]
When I sync library annotations, I get no errors, and the logs indicate it SHOULD work, but the annotations folder is empty. (Defold API annotations work fine.) This is after a fresh reboot. Not sure what to try next.

[defold-kit.log](https://github.com/astrochili/vscode-defold/files/14028319/defold-kit.log)

<img width="657" alt="image" src="https://github.com/astrochili/vscode-defold/assets/133168946/cc611f79-bf06-4ca4-b6e6-b9be26bd8370">

<img width="1538" alt="image" src="https://github.com/astrochili/vscode-defold/assets/133168946/87e02a40-40f8-42ec-a1e1-a660a77ad31f">

<img width="1181" alt="image" src="https://github.com/astrochili/vscode-defold/assets/133168946/f1146267-ed49-4134-be25-b406d255ec97">

**Comment by astrochili** [comment]
Hello,

> the annotations folder is empty.

You mean the folder `\Users\Alexis\AppData\Roaming\Code\User\workspaceStorage\3d2a6a1209dc231870fbc97df9373465\astronachos.defold\libs_api\` is empty?

**Comment by swajj** [comment]
> Hello,
> 
> > the annotations folder is empty.
> 
> You mean the folder `\Users\Alexis\AppData\Roaming\Code\User\workspaceStorage\3d2a6a1209dc231870fbc97df9373465\astronachos.defold\libs_api\` is empty?

correct, that folder is empty, even though it's the path shown in the output console and added to settings. Can't find any trace of the "Unpacking from..." operations anywhere.

**Comment by astrochili** [comment]
Interesting. I thought I had covered [every step with logs and checks](https://github.com/astrochili/vscode-defold/blob/104351f08047fc5d524f5e33587bddb0c361173f/src/annotations.ts#L226-L241), but not. Don't have ideas at the moment 🤔, need to reproduce it or debug in your environment.

If you're interested, debugging is relatively easy. You just need to open this repository in VS Code and run the debugger (all settings are already in this repository). A new VSCode instance with this extension will be launched and you will need to open the Defold project in it and start API synchronisation as usual.

**Comment by astrochili** [comment]
Ok, with the help of @ReanimatorXP we found the problems and fixed it. Yay!

**Comment by swajj** [comment]
Awesome, thanks! It's definitely syncing now. I am having trouble getting the LSP to actually SEE the annotations but I'll deal with that later when I have more time to dive in deeper.

**Comment by astrochili** [comment]
@swajj Hmm, what exactly is the bug? Make sure that Defold Kit set the correct path to the `Lua.workspace.library` property in the `settings.json` file like `.../workspaceStorage/[workspaceHashValue]/astronachos.defold`.

**Comment by swajj** [comment]
@astrochili that was all correct, I had to do some sluething but figured it out. I had this option enabled.
<img width="788" alt="image" src="https://github.com/astrochili/vscode-defold/assets/133168946/567468ba-3696-4e88-a6be-e874f6d26c47">

Not a high priority I'm sure, but the addon could probably at least warn someone that this setting will break library annotation support :) (and understandably so... once you know it's there buried in the mess of confusing options for the Lua Language Server addon :) ) thanks for all your help!
