### ISSUE TITLE
Join Forces?

### ISSUE THREAD

**Issue by thejustinwalsh** [astrochili/vscode-defold#4]
https://github.com/ts-defold/defold-vscode-build

Pro's doesn't require bash on windows, full power of nodejs api behind it, includes problem marchers to take you to errors from build or run output, colorized output, provides custom tasks that can be stacked with dependsOn, etc..

I can add you as a collaborator if interested?

**Comment by astrochili** [comment]
Closed by the release [2.0.0](https://github.com/astrochili/vscode-defold/releases/tag/2.0.0) 👏

**Comment by astrochili** [comment]
@thejustinwalsh Oh man, to be honest, all this time I thought your extension was for TypeScript development only. And now, when I started to prepare another [awesome-defold](https://github.com/astrochili/awesome-defold) repository, I realised...

**Comment by thejustinwalsh** [comment]
Haha, no worries! Having options is always a good place to be. I've had 2 kids and almost no time over the last two years, so glad to see the space moving forward! 🚀
